export const CLICK_PIECE = "CLICK_PIECE";
export const CLICK_STATION = "CLICK_STATION";
export const CLICK_CONNECTION = "CLICK_CONNECTION";
export const CLICK_COMMIT = "CLICK_COMMIT";
export const CLICK_UNCOMMIT = "CLICK_UNCOMMIT";
export const CLICK_UNDO = "CLICK_UNDO";
